export const baseURL = 'http://localhost:8000/api/v1'
export const loginEndpoint = '/login/'
export const registerEndpoint = '/authentication/users/'
export const accountEndpoint = '/bank-accounts/detail/'
export const bankAccountEndpointAll = '/bank-accounts/detailAll/'