export const baseURL = 'http://localhost:8000/api/v1'
export const loginEndpoint = '/accounts/login/'
export const registerEndpoint = '/accounts/register/'
export const accountEndpoint = '/bank-accounts/detail/'
export const accountEndpointAll = '/bank-accounts/detailAll/'